### ISSUE TITLE
Error in t2s conversion of 恭弘

### ISSUE THREAD

**Issue by Trey314159** [medcl/elasticsearch-analysis-stconvert#13]
Using the tsconvert tokenizer or char_filter, "恭弘" gets converted to "叶 叶 恭弘:叶:叶".

I think it is because of [line 4050 in t2s.properties](https://github.com/medcl/elasticsearch-analysis-stconvert/blob/master/src/main/resources/t2s.properties#L4050), which is weirdly formatted, and the only line with "=" in the whole file:
> 恭弘=叶 恭弘:叶

This causes downstream problems with SmartCN, and the character counts for tokens are wrong for everything on the same line that comes after.

I recompiled a copy of v1.8.5 without this line and 恭弘 is unchanged, which is definitely better if not ideal.

**Comment by Trey314159** [comment]
I found another potential problem on [line 3939](https://github.com/medcl/elasticsearch-analysis-stconvert/blob/master/src/main/resources/t2s.properties#L3939):
> 儸:﻿㑩

There is a zero-width no-break space to the right of the colon, which probably shouldn't be there.

**Comment by medcl** [comment]
@Trey314159 good catch, i will fix it

**Comment by medcl** [comment]
fixed in master, thanks
