### ISSUE TITLE
"手機"经过tokenFilter=stconvert后结果变成了"手","機". 不应该是"手机"吗? 

### ISSUE THREAD

**Issue by lintghi** [medcl/elasticsearch-analysis-stconvert#14]
#手機  %E6%89%8B%E6%A9%9F
curl -XGET http://localhost:9200/_analyze\?text\=%E6%89%8B%E6%A9%9F\&filter\=stconvert

{"tokens":[{"token":"手","start_offset":0,"end_offset":1,"type":"<IDEOGRAPHIC>","position":0},{"token":"機","start_offset":1,"end_offset":2,"type":"<IDEOGRAPHIC>","position":1}]}

版本: stconvert-1.9.3  es-2.4.3

**Comment by medcl** [comment]
默认是简体转繁体 可以换tsconvert试试么？
lintghi <notifications@github.com>于2017年3月31日 周五下午4:30写道：

**Comment by lintghi** [comment]
我试了用tsconvert: 
curl -XGET http://localhost:9200/_analyze\?text\=%E6%89%8B%E6%A9%9F\&filter\=tsconvert
结果一样.

{"tokens":[{"token":"手","start_offset":0,"end_offset":1,"type":"<IDEOGRAPHIC>","position":0},{"token":"機","start_offset":1,"end_offset":2,"type":"<IDEOGRAPHIC>","position":1}]}

**Comment by medcl** [comment]
```

PUT /stconvert/
{
    "index" : {
        "analysis" : {
            "analyzer" : {
                "tsconvert" : {
                    "tokenizer" : "tsconvert"
                    }
            },
            "tokenizer" : {
                "tsconvert" : {
                    "type" : "stconvert",
                    "delimiter" : "#",
                    "keep_both" : false,
                    "convert_type" : "t2s"
                }
            },
            "char_filter" : {
                "tsconvert" : {
                    "type" : "stconvert",
                    "delimiter" : "#",
                    "keep_both" : false,
                    "convert_type" : "t2s"
                }
            }
        }
    }
}


GET /stconvert/_analyze
{
  "text": ["手機"],
  "analyzer": "tsconvert"
}
```

```
{
  "tokens": [
    {
      "token": "手机",
      "start_offset": 0,
      "end_offset": 2,
      "type": "word",
      "position": 0
    }
  ]
}
```
