### ISSUE TITLE
找不到：tsconvert_keep_both 、stconvert_keep_both

### ISSUE THREAD

**Issue by gzliudan** [medcl/elasticsearch-analysis-stconvert#17]
能找到tsconvert和stconvert，但没找到：tsconvert_keep_both 和stconvert_keep_both

curl -XGET http://localhost:9200/stconvert/_analyze?text=%e5%8c%97%e4%ba%ac%e5%9b%bd%e9%99%85%e7%94%b5%e8%a7%86%e5%8f%b0%2c%e5%8c%97%e4%ba%ac%e5%9c%8b%e9%9a%9b%e9%9b%bb%e8%a6%96%e8%87%ba\&tokenizer=tsconvert_keep_both\&pretty

{
  "error" : {
    "root_cause" : [
      {
        "type" : "remote_transport_exception",
        "reason" : "[HadoopTemp][192.168.1.208:9300][indices:admin/analyze[s]]"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "failed to find tokenizer under [tsconvert_keep_both]"
  },
  "status" : 400
}

 curl -XGET http://localhost:9200/stconvert/_analyze?text=%e5%8c%97%e4%ba%ac%e5%9b%bd%e9%99%85%e7%94%b5%e8%a7%86%e5%8f%b0%2c%e5%8c%97%e4%ba%ac%e5%9c%8b%e9%9a%9b%e9%9b%bb%e8%a6%96%e8%87%ba\&tokenizer=stconvert_keep_both\&pretty
{
  "error" : {
    "root_cause" : [
      {
        "type" : "remote_transport_exception",
        "reason" : "[HadoopTemp][192.168.1.208:9300][indices:admin/analyze[s]]"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "failed to find tokenizer under [stconvert_keep_both]"
  },
  "status" : 400
}

**Comment by medcl** [comment]
这个默认没有了，需要自己custom一个。

**Comment by medcl** [comment]
```
PUT /stconvert/
{
    "index" : {
        "analysis" : {
            "analyzer" : {
                "tsconvert" : {
                    "tokenizer" : "tsconvert"
                    }
            },
            "tokenizer" : {
                "tsconvert_keep_both" : {
                    "type" : "stconvert",
                    "delimiter" : "#",
                    "keep_both" : true,
                    "convert_type" : "t2s"
                }
            }
        }
    }
}
```
