### ISSUE TITLE
请问在 elasticsearch.yml，如何配置自定义stconvert分词？

### ISSUE THREAD

**Issue by wuyu8995861** [medcl/elasticsearch-analysis-stconvert#18]
请问在 elasticsearch.yml，如何配置自定义stconvert分词？

**Comment by wuyu8995861** [comment]
PUT /stconvert/
{
    "index" : {
        "analysis" : {
            "analyzer" : {
                "tsconvert" : {
                    "tokenizer" : "tsconvert"
                    }
            },
            "tokenizer" : {
                "tsconvert" : {
                    "type" : "stconvert",
                    "delimiter" : "#",
                    "keep_both" : false,
                    "convert_type" : "t2s"
                }
            },
            "char_filter" : {
                "tsconvert" : {
                    "type" : "stconvert",
                    "delimiter" : "#",
                    "keep_both" : false,
                    "convert_type" : "t2s"
                }
            }
        }
    }
}

报错误

{
"error": {
"root_cause": [
{
"type": "index_creation_exception",
"reason": "failed to create index"
}
],
"type": "illegal_argument_exception",
"reason": "Unknown CharFilter type [stconvert] for [tsconvert]"
},
"status": 400
}

**Comment by medcl** [comment]
elasticsearch.yml 不需要修改配置。
直接用RESTful API，我这边没有复现，麻烦重新试下。
