### ISSUE TITLE
how to config stconvert in django-dsl?

### ISSUE THREAD

**Issue by zsk1993** [medcl/elasticsearch-analysis-stconvert#27]
html_strip = analyzer(
    'ik',
    tokenizer="ik_smart",
    filter=["standard", "lowercase", "stop", "snowball"],
    # char_filter=["html_strip"]
    # char_filter={
    #   "tsconvert" : {
    #     "convert_type": "t2s",
    #     "type": "stconvert"
    # }
    # }
    char_filter=["stconvert"]
)

I want to config the convert_type:t2s ,But there are errors:
elasticsearch.exceptions.TransportError: TransportError(500, 'settings_exception', 'Failed to load                  settings from [{"number_of_shards":3,"analysis":{"analyzer":{"ik":{"filter":["standard","lowercas                 e","stop","snowball"],"char_filter":[{"tsconvert":{"convert_type":"t2s","type":"stconvert"}}],"typ                 e":"custom","tokenizer":"ik_smart"}}},"number_of_replicas":1}]')

**Comment by medcl** [comment]
Sorry, I don't know about django-dsl, can you try to use the raw queryDSL, and then check the the json generated by the django-dsl.

**Comment by zsk1993** [comment]
thank you,I have resolved the question,the custom char_filter just like this:

tsconvert = char_filter(
    "tsconvert",
    type="stconvert",
    convert_type="t2s"
)
html_strip = analyzer(
    'ik',
    tokenizer="ik_smart",
    filter=["standard", "lowercase", "stop", "snowball"],
    char_filter=[tsconvert]
)

I need config the "tsconvert" in advance

**Comment by medcl** [comment]
great!
